const toggle=document.querySelector('.menu-toggle');const links=document.querySelector('.nav-links');const navItems=[...document.querySelectorAll('.nav-links a')];toggle?.addEventListener('click',()=>{const open=links.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});navItems.forEach(a=>a.addEventListener('click',()=>{links.classList.remove('open');toggle?.setAttribute('aria-expanded','false');}));

const motionStyle=document.createElement('style');motionStyle.textContent=`.reveal{opacity:0;transform:translateY(24px);transition:opacity .7s ease,transform .7s ease}.reveal.visible{opacity:1;transform:none}.reveal.delay-1{transition-delay:.08s}.reveal.delay-2{transition-delay:.16s}.reveal.delay-3{transition-delay:.24s}.ripple-target{position:relative;overflow:hidden}.ripple{position:absolute;border-radius:50%;transform:scale(0);animation:ripple .55s ease-out;background:rgba(192,132,252,.22);pointer-events:none}@keyframes ripple{to{transform:scale(3.5);opacity:0}}@media(prefers-reduced-motion:reduce){.reveal{opacity:1;transform:none;transition:none}.ripple{display:none}}`;document.head.appendChild(motionStyle);

const revealTargets=document.querySelectorAll('.section-label,.about-copy,.about-visual,.tech-card,.project,.services>div,.contact-grid>div,.footer');revealTargets.forEach((el,i)=>{el.classList.add('reveal');if(i%4===1)el.classList.add('delay-1');if(i%4===2)el.classList.add('delay-2');if(i%4===3)el.classList.add('delay-3');});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.12,rootMargin:'0px 0px -40px 0px'});revealTargets.forEach(el=>observer.observe(el));

document.querySelectorAll('.btn,.project>span').forEach(el=>{el.classList.add('ripple-target');el.addEventListener('click',e=>{const r=el.getBoundingClientRect(),size=Math.max(r.width,r.height)*.45;const ripple=document.createElement('span');ripple.className='ripple';ripple.style.width=ripple.style.height=size+'px';ripple.style.left=e.clientX-r.left-size/2+'px';ripple.style.top=e.clientY-r.top-size/2+'px';el.appendChild(ripple);ripple.addEventListener('animationend',()=>ripple.remove());});});

const sections=[...document.querySelectorAll('main section[id]')];const sectionObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){const active=document.querySelector(`.nav-links a[href="#${entry.target.id}"]`);if(active){navItems.forEach(n=>n.classList.remove('active'));active.classList.add('active');}}});},{rootMargin:'-35% 0px -55% 0px',threshold:0});sections.forEach(section=>sectionObserver.observe(section));
window.addEventListener('load',()=>{const first=document.querySelector('.nav-links a');if(first&&!document.querySelector('.nav-links a.active'))first.classList.add('active');});